services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    container_name: auth-service-backend
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: dev-secret
      DJANGO_DEBUG: "1"
      DJANGO_ADMIN_EMAIL: admin@example.com
      DJANGO_ADMIN_PASSWORD: admin123
      CORS_ALLOWED_ORIGINS: http://localhost:5173
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:                # 👈 añade este volumen para hot reload backend
      - ./backend:/app

volumes:
  db_data:
